# Inherit from the tembo-io/infrastructure repo
# https://runs-on.com/configuration/repo-config/
_extends: infrastructure

runners:
  cheap-runner:
    spot: lowest-price
    family: ["m7*", "c7*", "r7*", "t3*"]
    ram: [4, 512]
    cpu: [2, 128]
