{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "tembo-pod-init.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "tembo-pod-init.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Allow the release namespace to be overridden
*/}}
{{- define "tembo-pod-init.namespace" -}}
  {{- if .Values.namespaceOverride -}}
    {{- .Values.namespaceOverride -}}
  {{- else -}}
    {{- .Release.Namespace -}}
  {{- end -}}
{{- end -}}

{{/*
Generate labels to be used
*/}}
{{- define "tembo-pod-init.labels" -}}
app: {{ include "tembo-pod-init.fullname" . }}
chart: {{ template "tembo-pod-init.chart" . }}
release: {{ .Release.Name }}
heritage: {{ .Release.Service }}
{{- end }}

{{- define "tembo-pod-init-helm.labels" -}}
{{ include "tembo-pod-init.labels" . }}
app.kubernetes.io/name: {{ include "tembo-pod-init.fullname" . | quote }}
app.kubernetes.io/version: {{ .Chart.AppVersion }}
app.kubernetes.io/component: "admission"
{{- end }}
