apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-tls" (include "tembo-pod-init.namespace" .) (include "tembo-pod-init.fullname" .) }}
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
webhooks:
  - name: {{ printf "%s.%s.svc" (include "tembo-pod-init.fullname" .) (include "tembo-pod-init.namespace" .) }}
    clientConfig:
      service:
        name: {{ include "tembo-pod-init.fullname" . }}
        namespace: {{ template "tembo-pod-init.namespace" . }}
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
  - name: {{ printf "%s.%s.svc.cluster.local" (include "tembo-pod-init.fullname" .) (include "tembo-pod-init.namespace" .) }}
    clientConfig:
      service:
        name: {{ include "tembo-pod-init.fullname" . }}
        namespace: {{ template "tembo-pod-init.namespace" . }}
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
