apiVersion: v1
kind: Service
metadata:
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ include "tembo-pod-init.namespace" . }}
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ include "tembo-pod-init.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
