apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tembo-pod-init.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
