apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ include "tembo-pod-init.fullname" . }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
