nameOverride:
namespaceOverride:
logLevel: info
replicas: 1
initContainerImage:
  repository: quay.io/tembo/tembo-pg-cnpg
  tag: latest
image:
  repository: quay.io/tembo/tembo-pod-init 
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: Always

extraEnv: {}
annotations: {}
podAnnotations: {}
resources: {}

upgradeStrategy: RollingUpdate

service:
  type: "ClusterIP"
  port: 443
  targetPort: 8443
  annotations: {}

livenessProbe:
  httpGet:
    path: /health/liveness
    port: 8443
    scheme: HTTPS
  initialDelaySeconds: 15
readinessProbe:
  httpGet:
    path: /health/readiness
    port: 8443
    scheme: HTTPS
  failureThreshold: 3
  timeoutSeconds: 15
  periodSeconds: 15

# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

# https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
