name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: Build and push images
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    outputs:
      short_sha: ${{ steps.versions.outputs.SHORT_SHA }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check out the coredb repo to reuse some actions
        uses: actions/checkout@v3
        with:
          repository: coredb-io/coredb
          path: ./coredb
          ref: d62b2a2be30c0f70b34ad5283c4679361dedf852
      - name: Build and upload image
        uses: ./coredb/.github/actions/build-and-push-to-quay
        with:
          image_name: tembo-pod-init
          publish_latest: true
          publish_calver: true
          docker_directory: .
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

  argocd_update:
    name: ArgoCD update automation
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    strategy:
      # fail-fast means to cancel all jobs if one fails
      fail-fast: false
      matrix:
        include:
          - repository: coredb-io/app-deploy-dev
            subdirectory: dev
            branch: main
          # - repository: coredb-io/app-deploy
          #   subdirectory: staging
          #   branch: staging-updates
          # - repository: coredb-io/app-deploy
          #   subdirectory: prod
          #   branch: prod-updates
    needs:
      - build_and_push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the repo
        uses: ./.github/actions/argocd-update
        with:
          repository: ${{ matrix.repository }}
          ssh_key: ${{ secrets.SERVICE_USER_GITHUB_SSH_KEY }}
          branch: ${{ matrix.branch }}
          version: ${{ needs.build_and_push.outputs.short_sha }}
          subdirectory: ${{ matrix.subdirectory }}
