name: lint workflow

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - '/**'
  # Always run on main or release branches
  push:
    branches:
      - main
      - release**

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "lint"
      - name: Cargo format
        run: cargo +nightly fmt --all --check
      - name: Clippy
        run: cargo clippy

  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: unit-integration-tests
        env:
          NILE_TOKEN: ${{ secrets.NILE_TOKEN }}
        run: make test.integration
      - name: teardown
        run: make test.cleanup