name: Prometheus Exporter for Postgres

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: setup pgx
        run: cargo install --locked cargo-pgx

      - name: init
        run: cargo pgx init

      - name: test
        run: cargo pgx test
